### ISSUE TITLE
Issue with the learning rate used in the hyperparameter generator

### ISSUE THREAD

**Issue by pankaj-giri** [pankaj-giri/distributed_hyperparameter_search#2]
There seems to be a problem with the hyperparameter generator used. Getting the following stack trace..

`Traceback (most recent call last):
  File "ray_hyperparameter_search.py", line 57, in <module>
    print(ray.get(results))
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/ray/worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(InvalidArgumentError): ray::__main__.train_cnn_and_compute_accuracy() (pid=17324, ip=192.168.1.10)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "ray_hyperparameter_search.py", line 36, in train_cnn_and_compute_accuracy
    history = model.fit(x=train_images, y=train_labels, epochs=hyperparameters['epochs'])
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/preetika/anaconda3/envs/tensorflow_py3.7/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  lr is not a scalar : [2]
	 [[node Adam/Adam/update_7/ResourceApplyAdam (defined at ray_hyperparameter_search.py:36) ]] [Op:__inference_train_function_809]

Function call stack:
train_function`

**Comment by pankaj-giri** [comment]
Perhaps this may help..


return {'learning_rate': np.random.choice([0.001, 0.0001, 0.01]),
